# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-03-10 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Article Title')),
                ('summary', models.TextField(default='Article summary is equivalent to the description content of the webpage, please fill in ...', max_length=230, verbose_name='Article summary')),
                ('body', models.TextField(verbose_name='Article Content')),
                ('img_link', models.CharField(default='/static/blog/img/summary.png', max_length=255, verbose_name='Image address')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Modified time')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Article',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Number determines the order in which pictures are played, not more than 5 pictures', verbose_name='Number')),
                ('title', models.CharField(blank=True, help_text='Title can be empty', max_length=20, null=True, verbose_name='Title')),
                ('content', models.CharField(max_length=80, verbose_name='Description')),
                ('img_url', models.CharField(max_length=200, verbose_name='Image address')),
                ('url', models.CharField(default='#', help_text='Hyperlink for image jump, default # means no jump', max_length=200, verbose_name='Jump link')),
            ],
            options={
                'verbose_name': 'Picture Carousel',
                'verbose_name_plural': 'Picture Carousel',
                'ordering': ['number', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Article classification')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='Website description', help_text='Used as a description in SEO, the length refers to the SEO standard', max_length=240, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classification',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Site name')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Site description')),
                ('link', models.URLField(help_text='Please fill in the full form address starting with http or https', verbose_name='Friendly chain address')),
                ('logo', models.URLField(blank=True, help_text='Please fill in the full form address starting with http or https', verbose_name='Website Logo')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Whether active')),
                ('is_show', models.BooleanField(default=False, verbose_name='Whether the homepage is displayed')),
            ],
            options={
                'verbose_name': 'Friendly Link',
                'verbose_name_plural': 'Friendly Link',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Article Keywords')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keyword',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Silian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badurl', models.CharField(help_text='Note: The address is in the full link format starting with http', max_length=200, verbose_name='Dead chain address')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dead chain description')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of submission')),
            ],
            options={
                'verbose_name': 'Dead Link',
                'verbose_name_plural': 'Dead Link',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Article Tag')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='Website description', help_text='Used as a description in SEO, the length refers to the SEO standard', max_length=240, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Label',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=1, verbose_name='Position')),
                ('star_num', models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=3, verbose_name='Number of stars')),
                ('icon', models.CharField(default='fa fa-pencil', max_length=50, verbose_name='icon')),
                ('icon_color', models.CharField(choices=[('primary', 'Basic-Blue'), ('success', 'Success-Green'), ('info', 'Info-Sky Blue'), ('warning', 'Warning-orange'), ('danger', 'Danger-Red')], default='info', max_length=20, verbose_name='Icon Color')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('update_date', models.DateTimeField(verbose_name='Update time')),
                ('content', models.TextField(verbose_name='main content')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timeline',
                'ordering': ['update_date'],
            },
        ),
    ]
