# Generated by Django 2.1.15 on 2020-04-20 07:58

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200420_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='BlogContent'),
        ),
    ]
