# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-03-10 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Site Category Name')),
                ('order_num', models.IntegerField(default=99, help_text='Sequence number can be used to adjust the order, the smaller the more, the more forward', verbose_name='Sequence number')),
            ],
            options={
                'verbose_name': 'Tool Category',
                'verbose_name_plural': 'Tool Category',
                'ordering': ['order_num', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ToolLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Site name')),
                ('description', models.CharField(max_length=100, verbose_name='Site Description')),
                ('link', models.URLField(verbose_name='Site Link')),
                ('order_num', models.IntegerField(default=99, help_text='Sequence number can be used to adjust the order, the smaller the more the more forward', verbose_name='Sequence number')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.ToolCategory', verbose_name='Site Category')),
            ],
            options={
                'verbose_name': 'Recommended Tool',
                'verbose_name_plural': 'Recommended Tool',
                'ordering': ['order_num', 'id'],
            },
        ),
    ]
