# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-03-10 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('content', models.TextField(verbose_name='Comment Content')),
            ],
            options={
                'verbose_name': 'Post Comment',
                'verbose_name_plural': 'Post Comment',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Hint time')),
                ('is_read', models.BooleanField(default=False, verbose_name='Whether read')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_comment', to='comment.ArticleComment', verbose_name='Owned Comment')),
            ],
            options={
                'verbose_name': 'Prompt Message',
                'verbose_name_plural': 'Prompt Message',
                'ordering': ['-create_date'],
            },
        ),
    ]
